
spring.application.name=AITMK

server.ssl.key-store-type=JKS
server.port=6153
#server.ssl.key-store=C:\\Users\\xz\\Downloads\\22915792_crm.wondermindedu.com_jks\\crm.wondermindedu.com.jks
server.ssl.key-store=/home/AITMK/jks/crm.wondermindedu.com.jks
server.ssl.key-password=fmjppo9i

# ===== WhatsApp ?? =====
whatsapp.verify-token=your_verify_token_here
whatsapp.app-secret=your_app_secret_here
whatsapp.accessToken=EAAdmFSDk8iwBQyG4hK4S0TxXaw26NjLMBZCmHbSgyefFeHazEfKzmCK3M8DEH9e2BrNuAZAXfmBPxuVQ9mRYHJYdy2RPxKAr4HSJ8dd4VxjbnW6e3VhWedmgaQw4bhd3MoJid3XBK7Bz7IQtTS50ZCVxxcBo4pWnXKzXRkWIFDZBn7WDyuZAb5SRVRNrZAAQZDZD
whatsapp.graphUrl=https://graph.facebook.com/v22.0


# Dify AI
ai.dify.base-url=https://api.dify.ai
ai.dify.api-key=app-OtSFboBn7jjg4Q3HCrGAjWdE
# CRM OpenAPI
crm.base-url=https://crm.wondermindedu.com
crm.appKey=228dcfc251e08a83
crm.sign=MWM2ZGUwNWFmMDU2M2E5NzA5NmE3YTJiMjU5MWJlYTcxNjgxMjJiNjBjYmM2NjU5OTU5YzZiYWRhZDRhNDgwZA==
crm.ownerId=3c14f43a-da20-4abc-8dba-4afb368dc726

# 文件上传大小（默认1MB，调大以支持PPT等文档）
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
