package com.example.aitmk.service.v2;
import com.example.aitmk.model.api.v2.V2Api.*;import com.example.aitmk.model.entity.*;
import java.time.Instant;
public final class V2Mapper{private V2Mapper(){}
 public static MessageView message(ChatMessageEntity m){var media=hasMedia(m)?new MediaView(m.getMediaId(),m.getMediaUrl(),m.getMimeType(),m.getFileName()):null;return new MessageView(s(m.getId()),s(m.getConversationId()),s(m.getResourceId()),m.getExternalMessageId(),m.getClientRequestId(),m.getSenderType().name(),m.getSenderId(),m.getMessageType().name(),m.getContent(),media,m.getSentStatus().name(),m.getFailureCode(),m.getFailureReason(),m.getCreatedAt(),m.getSentAt(),m.getDeliveredAt(),m.getReadAt());}
 public static ResourceView resource(ResourceEntity r,ChatMessageEntity lastMessage){return new ResourceView(s(r.getId()),r.getCustomerPhone(),r.getCustomerName(),r.getSourceChannel().name(),r.getResourceType().name(),r.getResourceStatus().name(),r.getAssignedAgentId()==null?null:new AgentBrief(r.getAssignedAgentId(),null),lastMessage==null?null:message(lastMessage),r.getCreatedAt(),r.getUpdatedAt(),r.getVersion());}
 public static AssignmentView assignment(AssignmentRecordEntity a){return new AssignmentView(s(a.getId()),s(a.getResourceId()),s(a.getConversationId()),new AgentBrief(a.getAgentId(),null),a.getAssignedBy(),a.getAssignType().name(),a.getStatus().name(),a.isReplyable(),a.getAssignedAt(),a.getClosedAt(),a.getCloseReason());}
 public static ConversationSummary conversation(ConversationEntity c,ResourceEntity r,ConversationAgentStateEntity state,ChatMessageEntity lastMessage,boolean replyable){Instant deadline=r.getLastCustomerMessageAt()==null?null:r.getLastCustomerMessageAt().plusSeconds(86400);return new ConversationSummary(s(c.getId()),s(r.getId()),new CustomerBrief(r.getCustomerPhone(),r.getCustomerName()),c.getChannel().name(),c.getStatus().name(),r.getResourceStatus().name(),c.getAiState().name(),c.getAssignedAgentId()==null?null:new AgentBrief(c.getAssignedAgentId(),null),replyable,deadline,state==null?0:state.getUnreadCount(),state==null?null:s(state.getLastReadMessageId()),lastMessage==null?null:message(lastMessage),c.getCreatedAt(),c.getClosedAt(),c.getCloseReason(),c.getVersion());}
 private static boolean hasMedia(ChatMessageEntity m){return m.getMessageType()!=com.example.aitmk.model.entity.PersistenceEnums.MessageType.TEXT&&(m.getMediaId()!=null||m.getMediaUrl()!=null||m.getMimeType()!=null||m.getFileName()!=null);}
 public static String s(Long id){return id==null?null:id.toString();}
}
